### ISSUE TITLE
Investigate Nuxt integration

### ISSUE THREAD

**Issue by styts** [phaidra/phaidra-ui#10]

**Comment by RastislavHudak** [comment]
I had a look at SEO/SSR and while it seems like at least googlebot can see a js rendered page, it might still have issues with async data loading. I also tested current phaidra-ui with google search console and it won't see anything (the search console reports some js errors). I also read that, because crawling js pages was unreliable, google recommends the pages to be rendered on server.

So: we'll need SSR. But we only need it for object detail page and some static pages (contact, impressum, policies....). The static pages can be [prerendered](https://github.com/chrisvfritz/prerender-spa-plugin), so that's not a problem. The object detail page must be rendered on server, but it should not be too complicated, it only calls api and solr and I think I could make an API method which will deliver all necessary data, so it would only call api - one call.

I suggest that the rest of the application stays in SPA mode, because it seems to me way easier to manage (session, multilanguage, .... also, current version 0.3.37 of phaidra-vue-components does not work in SSR) and we don't need SSR for anything there.

So if we need an app which runs in both modes, we can:
* use nuxt and [selectively enable SSR](https://blog.lichter.io/posts/selectively-enable-ssr-or-spa-mode-in-a-nuxtjs-ap/) for detail pages - I'm looking into this right now
* use vue as now, and figure out how to selectively enable [SSR](https://ssr.vuejs.org/) there

**Comment by RastislavHudak** [comment]
The boilerplate is SSR now.
